"""initial schema

Revision ID: 28760d50b69b
Revises:
Create Date: 2026-09-08 00:36:02.460667
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import hermes_home.storage.types


revision = "28760d50b69b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("parent_zone_id", sa.Integer(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_zone_id"], ["zones.id"], name=op.f("fk_zones_parent_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zones")),
        sa.UniqueConstraint("key", name=op.f("uq_zones_key")),
    )
    op.create_table(
        "entity_zones",
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_entity_zones_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_entity_zones")),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=36), nullable=False),
        sa.Column("incident_type", sa.String(length=64), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("started_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.Column("ended_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=1024), nullable=True),
        sa.Column("correlator", sa.String(length=64), nullable=False),
        sa.Column("correlator_version", sa.Integer(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.Column("updated_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name=op.f("fk_incidents_zone_id_zones")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("uid", name=op.f("uq_incidents_uid")),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_started_at"), ["started_at"], unique=False)

    op.create_table(
        "zone_edges",
        sa.Column("from_zone_id", sa.Integer(), nullable=False),
        sa.Column("to_zone_id", sa.Integer(), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_zone_id"], ["zones.id"], name=op.f("fk_zone_edges_from_zone_id_zones")
        ),
        sa.ForeignKeyConstraint(
            ["to_zone_id"], ["zones.id"], name=op.f("fk_zone_edges_to_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint(
            "from_zone_id", "to_zone_id", "relation", name=op.f("pk_zone_edges")
        ),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=36), nullable=False),
        sa.Column("delivery_key", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_entity_id", sa.String(length=255), nullable=True),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.Column("received_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.Column(
            "source_state_ts", hermes_home.storage.types.UtcDateTime(length=32), nullable=True
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column("created_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_events_incident_id_incidents")
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], name=op.f("fk_events_zone_id_zones")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("delivery_key", name=op.f("uq_events_delivery_key")),
        sa.UniqueConstraint("uid", name=op.f("uq_events_uid")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_events_content_hash", ["content_hash", "occurred_at"], unique=False
        )
        batch_op.create_index(
            "ix_events_entity_occurred", ["source_entity_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_events_incident_id", ["incident_id"], unique=False)
        batch_op.create_index("ix_events_occurred_at", ["occurred_at"], unique=False)
        batch_op.create_index(
            "ix_events_type_occurred", ["event_type", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_events_zone_occurred", ["zone_id", "occurred_at"], unique=False)

    op.create_table(
        "event_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("observation", sa.JSON(), nullable=True),
        sa.Column("observation_schema_version", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=True),
        sa.Column("started_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.Column("completed_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("artifact_bytes", sa.Integer(), nullable=True),
        sa.Column("artifact_width", sa.Integer(), nullable=True),
        sa.Column("artifact_height", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_analyses_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_analyses")),
        sa.UniqueConstraint("event_id", "attempt", "kind", name="event_attempt_kind"),
    )
    with op.batch_alter_table("event_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_event_analyses_event_id_status", ["event_id", "status"], unique=False
        )

    op.create_table(
        "event_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=36), nullable=False),
        sa.Column("received_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("delivery_key", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=False
        ),
        sa.Column(
            "lease_expires_at", hermes_home.storage.types.UtcDateTime(length=32), nullable=True
        ),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.String(length=1024), nullable=True),
        sa.Column("disposition", sa.String(length=24), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.Column("raw_body", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_deliveries_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_deliveries")),
        sa.UniqueConstraint("uid", name=op.f("uq_event_deliveries_uid")),
    )
    with op.batch_alter_table("event_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_deliveries_delivery_key"), ["delivery_key"], unique=False
        )
        batch_op.create_index("ix_event_deliveries_disposition", ["disposition"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_event_deliveries_received_at"), ["received_at"], unique=False
        )
        batch_op.create_index(
            "ix_event_deliveries_status_next_attempt_at",
            ["status", "next_attempt_at"],
            unique=False,
        )

    op.create_table(
        "event_tags",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_tags_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "tag", name=op.f("pk_event_tags")),
    )
    with op.batch_alter_table("event_tags", schema=None) as batch_op:
        batch_op.create_index("ix_event_tags_tag_event_id", ["tag", "event_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_event_tags_tag_event_id")

    op.drop_table("event_tags")
    with op.batch_alter_table("event_deliveries", schema=None) as batch_op:
        batch_op.drop_index("ix_event_deliveries_status_next_attempt_at")
        batch_op.drop_index(batch_op.f("ix_event_deliveries_received_at"))
        batch_op.drop_index("ix_event_deliveries_disposition")
        batch_op.drop_index(batch_op.f("ix_event_deliveries_delivery_key"))

    op.drop_table("event_deliveries")
    with op.batch_alter_table("event_analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_event_analyses_event_id_status")

    op.drop_table("event_analyses")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_zone_occurred")
        batch_op.drop_index("ix_events_type_occurred")
        batch_op.drop_index("ix_events_occurred_at")
        batch_op.drop_index("ix_events_incident_id")
        batch_op.drop_index("ix_events_entity_occurred")
        batch_op.drop_index("ix_events_content_hash")

    op.drop_table("events")
    op.drop_table("zone_edges")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_started_at"))

    op.drop_table("incidents")
    op.drop_table("entity_zones")
    op.drop_table("zones")
    # ### end Alembic commands ###
